site_name: Safari Documentation
site_url : https://safarigodocumentation.com/

theme:
  name: material
  palette:
    primary: green
    accent: teal
  highlightjs: true
  hljs_languages:
    - yaml
    - rust

nav:
  - Sommaire: 1.presentationDocument.md
  - Configuration: 2.configuration.md
  - Decouverte animaux: 3.Découverteanimaux.md
  - Safari Explorer: 4.explorerSafari.md
  - Nourir animaux: 5.nourirAnimaux.md
  - Apprendre: 6.apprentisage.md
